server:
  port: 3001

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/gmo
      username: postgres
      password: archesadmin
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        stat:
          log-slow-sql: true
          db-type: postgresql
          enabled: true
      # druid管理界面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: archesadmin
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: GMCWSOCEIPMWKBRF
    username: xyf1224626810@163.com
    port: 25
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
#    listener:
#      simple:
#        #开启手动确认
#        acknowledge-mode: manual

#  redis:
#    timeout: 10000ms
#    #服务器端口
#    host: 127.0.0.1
#    #服务器端口
#    port: 6379
#    #数据库
#    database: 0
#    #
#    password: 123456
#    lettuce:
#      pool:
#        #最大连接数
#        max-active: 1024
#        #最大连接阻塞等待时间
#        max-wait: 10000ms
#        #最大空闲连接
#        max-idle: 200
#        #最小空闲连接
#        min-idle: 5