server:
  port: 3009

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: GMCWSOCEIPMWKBRF
    username: xyf1224626810@163.com
    port: 25
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest